//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeyahatIstanbul.App_Start {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeyahatIstanbul.App_Start.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string chEmail {
            get {
                return ResourceManager.GetString("chEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi unuttum ?.
        /// </summary>
        public static string chForgotPassword {
            get {
                return ResourceManager.GetString("chForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string chName {
            get {
                return ResourceManager.GetString("chName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string chPassword {
            get {
                return ResourceManager.GetString("chPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar.
        /// </summary>
        public static string chPasswordSame {
            get {
                return ResourceManager.GetString("chPasswordSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string chSurname {
            get {
                return ResourceManager.GetString("chSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tc.
        /// </summary>
        public static string chTc {
            get {
                return ResourceManager.GetString("chTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkiye İletişim Bilgilesi.
        /// </summary>
        public static string comPlace_1 {
            get {
                return ResourceManager.GetString("comPlace_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almanya İletişim Bilgilesi.
        /// </summary>
        public static string comPlace_2 {
            get {
                return ResourceManager.GetString("comPlace_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Oluştur.
        /// </summary>
        public static string descRegister {
            get {
                return ResourceManager.GetString("descRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        public static string dtBirthDate {
            get {
                return ResourceManager.GetString("dtBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apart Seçiniz.
        /// </summary>
        public static string lblSelectApart {
            get {
                return ResourceManager.GetString("lblSelectApart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimi.
        /// </summary>
        public static string lblSelectMoney {
            get {
                return ResourceManager.GetString("lblSelectMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tur Seçiniz.
        /// </summary>
        public static string lblSelectTour {
            get {
                return ResourceManager.GetString("lblSelectTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arac Seçiniz.
        /// </summary>
        public static string lblSelectVehicle {
            get {
                return ResourceManager.GetString("lblSelectVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslim Almak İstediğiniz Yer.
        /// </summary>
        public static string lblSlctVehPlace1 {
            get {
                return ResourceManager.GetString("lblSlctVehPlace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslim Etmek İstediğniz Yer.
        /// </summary>
        public static string lblSlctVehPlace2 {
            get {
                return ResourceManager.GetString("lblSlctVehPlace2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tur Tarihi.
        /// </summary>
        public static string lblTourDate {
            get {
                return ResourceManager.GetString("lblTourDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Bu e-posta adresi kullanılmaktadır. E-posta adresi size ait ise giriş yapabilirsiniz; yoksa e-posta adresini değiştiriniz.&quot;.
        /// </summary>
        public static string lblUserEror_1 {
            get {
                return ResourceManager.GetString("lblUserEror_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alış Tarihi ve Saatiniz.
        /// </summary>
        public static string lblVehDate1 {
            get {
                return ResourceManager.GetString("lblVehDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veriş Tarihi ve Saatiniz.
        /// </summary>
        public static string lblVehDate2 {
            get {
                return ResourceManager.GetString("lblVehDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Girişi.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string menuAbout {
            get {
                return ResourceManager.GetString("menuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartlar.
        /// </summary>
        public static string menuApartList {
            get {
                return ResourceManager.GetString("menuApartList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string menuCommunication {
            get {
                return ResourceManager.GetString("menuCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string menuHome {
            get {
                return ResourceManager.GetString("menuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstanbul Turları.
        /// </summary>
        public static string menuTourlist {
            get {
                return ResourceManager.GetString("menuTourlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araçlar.
        /// </summary>
        public static string menuVehicleList {
            get {
                return ResourceManager.GetString("menuVehicleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Üye.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet.
        /// </summary>
        public static string rfSexId {
            get {
                return ResourceManager.GetString("rfSexId", resourceCulture);
            }
        }
    }
}
