//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeyahatIstanbul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCustomer
    {
        public int sqAccountCustomerId { get; set; }
        public Nullable<int> rfAccountId { get; set; }
        public Nullable<int> rfCustomerId { get; set; }
        public string chPosition { get; set; }
        public string chDesc { get; set; }
        public Nullable<bool> blStatus { get; set; }
        public string cdCreator { get; set; }
        public Nullable<System.DateTime> dtCreated { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
