//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeyahatIstanbul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Price = new HashSet<Price>();
            this.Process = new HashSet<Process>();
            this.Images = new HashSet<Images>();
            this.LogTable = new HashSet<LogTable>();
        }
    
        public short sqCategoryId { get; set; }
        public string chValue { get; set; }
        public Nullable<short> rfParentCategoryId { get; set; }
        public Nullable<short> rfCategoryTypeId { get; set; }
        public Nullable<byte> dgTimeOut { get; set; }
        public string chDesc { get; set; }
        public Nullable<bool> blStatus { get; set; }
        public string cdCreator { get; set; }
        public Nullable<System.DateTime> dtCreated { get; set; }
        public string chUrl { get; set; }
        public string chGuid { get; set; }
    
        public virtual CategoryType CategoryType { get; set; }
        public virtual ICollection<Price> Price { get; set; }
        public virtual ICollection<Process> Process { get; set; }
        public virtual ICollection<Images> Images { get; set; }
        public virtual ICollection<LogTable> LogTable { get; set; }
    }
}
