//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeyahatIstanbul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.AccountCustomer = new HashSet<AccountCustomer>();
            this.CustomerAddress = new HashSet<CustomerAddress>();
            this.CustomerCommunication = new HashSet<CustomerCommunication>();
            this.Process = new HashSet<Process>();
        }
    
        public int sqCustomerId { get; set; }
        public string chName { get; set; }
        public string chSurname { get; set; }
        public Nullable<System.DateTime> dtBirthDate { get; set; }
        public string chTc { get; set; }
        public Nullable<byte> rfSexId { get; set; }
        public Nullable<byte> rfCustomerTypeId { get; set; }
        public string chEmail { get; set; }
        public string chPassword { get; set; }
        public Nullable<bool> blPasswordExchange { get; set; }
        public string chDesc { get; set; }
        public Nullable<bool> blStatus { get; set; }
        public string cdCreator { get; set; }
        public Nullable<System.DateTime> dtCreated { get; set; }
    
        public virtual ICollection<AccountCustomer> AccountCustomer { get; set; }
        public virtual ICollection<CustomerAddress> CustomerAddress { get; set; }
        public virtual ICollection<CustomerCommunication> CustomerCommunication { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual Sex Sex { get; set; }
        public virtual ICollection<Process> Process { get; set; }
    }
}
