//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeyahatIstanbul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int SqImageId { get; set; }
        public Nullable<short> rfCategory { get; set; }
        public Nullable<int> rfDestination { get; set; }
        public string chImageName { get; set; }
        public string chRoute { get; set; }
        public string chUrl { get; set; }
        public string cdCreator { get; set; }
        public Nullable<System.DateTime> dtCreated { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
