//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeyahatIstanbul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int sqPriceId { get; set; }
        public Nullable<short> rfCategoryId { get; set; }
        public Nullable<int> rfProductId { get; set; }
        public Nullable<int> dgValue { get; set; }
        public string chDesc { get; set; }
        public Nullable<bool> blStatus { get; set; }
        public string cdCreator { get; set; }
        public Nullable<System.DateTime> dtCreated { get; set; }
        public Nullable<int> dgDay { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
