//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeyahatIstanbul.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeyahatIstanbulEntities : DbContext
    {
        public SeyahatIstanbulEntities()
            : base("name=SeyahatIstanbulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<AccountAddress> AccountAddress { get; set; }
        public DbSet<AccountCustomer> AccountCustomer { get; set; }
        public DbSet<Address> Address { get; set; }
        public DbSet<AddressType> AddressType { get; set; }
        public DbSet<Brand> Brand { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<CategoryType> CategoryType { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<CommunicationType> CommunicationType { get; set; }
        public DbSet<County> County { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<CustomerAddress> CustomerAddress { get; set; }
        public DbSet<CustomerCommunication> CustomerCommunication { get; set; }
        public DbSet<CustomerType> CustomerType { get; set; }
        public DbSet<ErrorLog> ErrorLog { get; set; }
        public DbSet<FuelType> FuelType { get; set; }
        public DbSet<GearType> GearType { get; set; }
        public DbSet<Model> Model { get; set; }
        public DbSet<Permission> Permission { get; set; }
        public DbSet<Price> Price { get; set; }
        public DbSet<Process> Process { get; set; }
        public DbSet<ProcessStatus> ProcessStatus { get; set; }
        public DbSet<RentApart> RentApart { get; set; }
        public DbSet<RentVehicle> RentVehicle { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<RolePermission> RolePermission { get; set; }
        public DbSet<Sex> Sex { get; set; }
        public DbSet<Tour> Tour { get; set; }
        public DbSet<TourType> TourType { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<UserType> UserType { get; set; }
        public DbSet<VehicleType> VehicleType { get; set; }
        public DbSet<Images> Images { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<LogTable> LogTable { get; set; }
        public DbSet<CommonSettings> CommonSettings { get; set; }
    }
}
